### ISSUE TITLE
Product Backlog Website Idea

### ISSUE THREAD

**Issue by yunjins** [KaylaCrush/group3project#12]
As a web user

I need to know more about IT technology

So that I can expand my knowledge on IT

## Tasks
- [x] Create new HTML pages #3 
- [x] Research technical topic - Machine Learning - #5 
- [x] Add CSS #7 
- [x] Create new machine learning page #8 
- [x] Research technical topics - Any topic #9 
- [x] Create new AI page #11 
- [x] Create new HTML page - High Level programming languages #14 
- [x] Remove weird formatting from index #15

**Comment by yunjins** [comment]
going to add the rest of the tasks for this sprint into the backlog

**Comment by KaylaCrush** [comment]
We did it everybody

**Comment by mirembekaggwa** [comment]
Woot!Sent via the Samsung Galaxy S8+
-------- Original message --------From: Kayla ***@***.***> Date: 3/14/24  3:41 PM  (GMT-08:00) To: KaylaCrush/group3project ***@***.***> Cc: Mirembe ***@***.***>, Assign ***@***.***> Subject: Re: [KaylaCrush/group3project] Product Backlog Website Idea (Issue
  #12) 
Closed #12 as completed.
